services:
  metadata-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata-server-1
    environment:
      - MODE=server
      - SERVER_ID=1
      - PORT=8081
    ports:
      - "8081:8081"

  metadata-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata-server-2
    environment:
      - MODE=server
      - SERVER_ID=2
      - PORT=8082
    ports:
      - "8082:8082"

  metadata-server-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata-server-3
    environment:
      - MODE=server
      - SERVER_ID=3
      - PORT=8083
    ports:
      - "8083:8083"

  router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: router
    environment:
      - MODE=router
      - PORT=8000
      - SERVERS=http://metadata-server-1:8081,http://metadata-server-2:8082,http://metadata-server-3:8083
    ports:
      - "8000:8000"
    depends_on:
      - metadata-server-1
      - metadata-server-2
      - metadata-server-3
    networks:
      - dfs-network

networks:
  dfs-network:
    driver: bridge
